export SNORKELHOME="`pwd`/snorkel-tables"
echo "Snorkel home directory: $SNORKELHOME"
export GWASKBHOME="`pwd`/src"
echo "GWASkb home directory: $GWASKBHOME"
# export PYTHONPATH="$PYTHONPATH:$SNORKELHOME:$SNORKELHOME/treedlib:$GWASKBHOME"
export PYTHONPATH="$PYTHONPATH:$SNORKELHOME:$SNORKELHOME/treedlib:$SNORKELHOME/treedlib/treedlib:$GWASKBHOME"
export PATH="$PATH:$SNORKELHOME:$SNORKELHOME/treedlib"
echo "Environment variables set!"
