export SNORKELHOME="`pwd`/snorkel-tables"
echo "Snorkel home directory: $SNORKELHOME"
export GWASDBHOME="`pwd`/src"
echo "GwasDB home directory: $GWASDBHOME"
# export PYTHONPATH="$PYTHONPATH:$SNORKELHOME:$SNORKELHOME/treedlib:$GWASDBHOME"
export PYTHONPATH="$PYTHONPATH:$SNORKELHOME:$SNORKELHOME/treedlib:$SNORKELHOME/treedlib/treedlib:$GWASDBHOME"
export PATH="$PATH:$SNORKELHOME:$SNORKELHOME/treedlib"
echo "Environment variables set!"
